version: "3.4"
services:
  mysql:
    hostname: mysql-master
    image: novice/mysql:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/data/mysql_test/mysql:/var/lib/mysql"
    configs:
      - source: my_config
        target: /var/www/notes.txt
        uid: '103'
        gid: '103'
        mode: 0440
    # networks:
    #   - webnet
  mysql-bak:
    hostname: mysql-slave
    image: novice/mysql:latest
    depends_on:
      - mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/data/mysql_test/mysql_bak:/var/lib/mysql"
    command: [mysql]
#     networks:
#       - webnet
  mysql-bak1:
    hostname: mysql-slave1
    image: novice/mysql:latest
    depends_on:
      - mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/data/mysql_test/mysql_bak1:/var/lib/mysql"
    configs:
      - source: my_config
        target: /var/www/notes.txt
    command: [mysql]
configs:
  my_config:
    file: ./notes
# networks:
#   webnet:

# docker stack deploy -c test.yml mysql
# docker rm $(docker ps -qa --no-trunc --filter "status=exited")
# docker stack rm mysql