version: "3.4"
services:
  mysql:
    hostname: mysql-master
    image: novice/mysql:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/data/mysql_test/mysql:/var/lib/mysql"
    # networks:
    #   - webnet
  mysql-bak:
    hostname: mysql-slave
    image: novice/mysql:latest
    depends_on:
      - mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/data/mysql_test/mysql_bak:/var/lib/mysql"
    command: [mysql]
#     networks:
#       - webnet
  mysql-bak1:
    hostname: mysql-slave1
    image: novice/mysql:latest
    depends_on:
      - mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/data/mysql_test/mysql_bak1:/var/lib/mysql"
    command: [mysql]
# networks:
#   webnet:

# docker stack deploy -c test.yml mysql
# docker rm $(docker ps -qa --no-trunc --filter "status=exited")
# docker stack rm mysql